
/* MAIN */

const UNIGRAMS_LENGTH = 30;
const BIGRAMS_LENGTH = 60;
const TRIGRAMS_LENGTH = 70;

const DATASET_PERC = 0.5;
const TRAINING_PERC = 0.7;
const TEST_PERC = 0.3;

/* EXPORT */

export {UNIGRAMS_LENGTH, BIGRAMS_LENGTH, TRIGRAMS_LENGTH};
export {DATASET_PERC, TRAINING_PERC, TEST_PERC};
